### ISSUE TITLE
Including xsubs.tv in list of subtitles providers

### ISSUE THREAD

**Issue by markossio** [bramwalet/Subliminal.bundle#13]
Helllo,

first of all, congrats on the plugin; works great. 

Is there an easy way to include xsubs.tv in the list of subtitles providers? Could i do it myself? If yes, short instructions would be much appreciated :-)

Cheers,
Markos

**Comment by bramwalet** [comment]
Hi, 

This plugin uses the Subliminal [1] project to find subtitles in Plex. Adding providers should happen in Subliminal, because I don't want to have my own 'fork'  of Subliminal inside this Plex bundle. 
When Subliminal accepts the provider, this Plex bundle can be updated with the latest version of Subliminal.

You are free to fork Subliminal, this Plex bundle and start coding :) 

[1] = https://github.com/Diaoul/subliminal
